### ISSUE TITLE
CVXGEN doesn't compile in cmake on my x64 ubuntu 14.04

### ISSUE THREAD

**Issue by jefesaurus** [rdeits/iris-distro#13]
Character escapes didn't function with the matlab call to generate the mex in "cvxgen/CMakelists.txt"
So the make command errored out.

Fixed by changing the relevant part of "cvxgen/CMakelists.txt" to:
```
set (MATLAB_EXEC "matlab" "-nodesktop" "-nosplash" "-r")
set (MATLAB_CMD "make_csolve,exit")
add_custom_command(OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/cvxgen_ldp_mex.${mex_suffix}
  COMMAND ${MATLAB_EXEC} ${MATLAB_CMD}
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
```

**Comment by rdeits** [comment]
Ah, interesting. Good catch! Can you open a pull request with your fix?

**Comment by jefesaurus** [comment]
Oops, I've discovered it was due to my matlab launcher script. Having now changed that to a soft link, it works well as it is.

**Comment by rdeits** [comment]
Okay, thanks!
