### ISSUE TITLE
compile error on mac

### ISSUE THREAD

**Issue by RussTedrake** [rdeits/iris-distro#14]
tried updating to the latest branch in drake-distro, but got this error compiling on my mac:

[100%] Building C object cvxgen/CMakeFiles/iris_ldp.dir/util.c.o
Linking C shared library ../lib/libiris_ldp.dylib
Undefined symbols for architecture x86_64:
  "_params", referenced from:
      _multbymA in matrix_support.c.o
      _multbymAT in matrix_support.c.o
      _fill_KKT in ldl.c.o
  "_settings", referenced from:
      _set_defaults in solver.c.o
      _set_start in solver.c.o
      _refine in solver.c.o
      _solve in solver.c.o
      _ldl_solve in ldl.c.o
      _ldl_factor in ldl.c.o
  "_vars", referenced from:
      _setup_pointers in solver.c.o
      _setup_indexing in solver.c.o
      _solve in solver.c.o
  "_work", referenced from:
      _eval_gap in solver.c.o
      _setup_pointers in solver.c.o
      _setup_indexing in solver.c.o
      _set_start in solver.c.o
      _eval_objv in solver.c.o
      _fillrhs_aff in solver.c.o
      _fillrhs_cc in solver.c.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [lib/libiris_ldp.dylib] Error 1
make[2]: *** [cvxgen/CMakeFiles/iris_ldp.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by rdeits** [comment]
I'm almost ready to switch over to the new c++ implementation, so I'll fix
this as part of that transition
