### ISSUE TITLE
osx compile error

### ISSUE THREAD

**Issue by empireryan** [rdeits/iris-distro#26]
Running make gets me:
[  2%] Performing build step for 'cdd_project'
Making all in lib-src
Making all in src
Making all in lib-src-gmp
Making all in src-gmp
libtool: link: gcc -g -O2 -o .libs/fourier_gmp fourier.o  -L/usr/local/lib ../lib-src-gmp/.libs/libcddgmp.dylib
Undefined symbols for architecture x86_64:
  "___gmpq_clear", referenced from:
      _main in fourier.o
  "___gmpq_init", referenced from:
      _main in fourier.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [fourier_gmp] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [cdd_project-prefix/src/cdd_project-stamp/cdd_project-build] Error 2
make[2]: *** [CMakeFiles/cdd_project.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by rdeits** [comment]
Can you try installing `gmp`? The easiest way is with [homebrew](http://brew.sh/):

```
brew install gmp
```

**Comment by empireryan** [comment]
I did a gmp install with `port install`. Just uninstalled, and reran with brew and I'm getting the same errors.

**Comment by rdeits** [comment]
Interesting. The build is actually failing while trying to install [cddlib](http://www.inf.ethz.ch/personal/fukudak/cdd_home/). I've built it successfully on OSX in the past, but it looks like it's still not finding your gmp library. A few options:

* run `make VERBOSE=1` so we can look at the exact compiler and linker flags
* install cddlib yourself, and then tell IRIS not to build it. You can do that by running `make options` and turning WITH_CDD to OFF

**Comment by empireryan** [comment]
the verbose option yields:
`cmake --build pod-build --config "Release"
/opt/local/bin/cmake -H/Users/empire/Documents/GitHub/iris-distro -B/Users/empire/Documents/GitHub/iris-distro/pod-build --check-build-system CMakeFiles/Makefile.cmake 0
/opt/local/bin/cmake -E cmake_progress_start /Users/empire/Documents/GitHub/iris-distro/pod-build/CMakeFiles /Users/empire/Documents/GitHub/iris-distro/pod-build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cdd_project.dir/build.make CMakeFiles/cdd_project.dir/depend
cd /Users/empire/Documents/GitHub/iris-distro/pod-build && /opt/local/bin/cmake -E cmake_depends "Unix Makefiles" /Users/empire/Documents/GitHub/iris-distro /Users/empire/Documents/GitHub/iris-distro /Users/empire/Documents/GitHub/iris-distro/pod-build /Users/empire/Documents/GitHub/iris-distro/pod-build /Users/empire/Documents/GitHub/iris-distro/pod-build/CMakeFiles/cdd_project.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cdd_project.dir/build.make CMakeFiles/cdd_project.dir/build
[  2%] Performing build step for 'cdd_project'
cd /Users/empire/Documents/GitHub/iris-distro/pod-build/cdd_project-prefix/src/cdd_project && make
Making all in lib-src
make[5]: Nothing to be done for `all'.
Making all in src
make[5]: Nothing to be done for `all'.
Making all in lib-src-gmp
make[5]: Nothing to be done for `all'.
Making all in src-gmp
/bin/sh ../libtool --tag=CC   --mode=link gcc  -g -O2 -L/usr/local/lib  -o fourier_gmp fourier.o ../lib-src-gmp/libcddgmp.la
libtool: link: gcc -g -O2 -o .libs/fourier_gmp fourier.o  -L/usr/local/lib ../lib-src-gmp/.libs/libcddgmp.dylib
Undefined symbols for architecture x86_64:
  "___gmpq_clear", referenced from:
      _main in fourier.o
  "___gmpq_init", referenced from:
      _main in fourier.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [fourier_gmp] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [cdd_project-prefix/src/cdd_project-stamp/cdd_project-build] Error 2
make[2]: *** [CMakeFiles/cdd_project.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2`

Made cddliv and configured the options as you recommended and it looks like that cleared things up. Many thanks for being so quick about this!

**Comment by rdeits** [comment]
Excellent!
