### ISSUE TITLE
MacPorts: ./cddmp.h:31:11: fatal error: 'gmp.h' file not found

### ISSUE THREAD

**Issue by edowson** [rdeits/iris-distro#27]
I get the following error while trying to build iris-bistro, as part of a drake-superbuild, using MacPorts 2.3.4 on Mac OS X 10.10.5 with Xcode 7.0.0 and MATLAB R2015a.

```
[  5%] Performing build step for 'cdd_project'
Making all in lib-src
Making all in src
Making all in lib-src-gmp
libtool: compile:  gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"cddlib\" -DVERSION=\"0.94\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBGMP=1 -DSTDC_HEADERS=1 -I. -I/usr/local/include -DGMPRATIONAL -g -O2 -MT cddcore.lo -MD -MP -MF .deps/cddcore.Tpo -c cddcore.c  -fno-common -DPIC -o .libs/cddcore.o
In file included from cddcore.c:14:
In file included from ./cdd.h:18:
./cddmp.h:31:11: fatal error: 'gmp.h' file not found
 #include "gmp.h"
          ^
1 error generated.
```

With a HomeBrew installation, the gmp.h header file can be found because it is installed by default into /usr/local/include.

MacPorts however, installs the gmp.h header file into /opt/local/include

Adding the CXXFLAGS='-I/opt/local/include' does not work :

```
if (IRIS_WITH_CDD)
	set(CDD_PROJECT_SRC_DIR ${CMAKE_CURRENT_BINARY_DIR}/cdd_project-prefix/src/cdd_project)
	ExternalProject_Add(cdd_project
		URL ftp://ftp.ifor.math.ethz.ch/pub/fukuda/cdd/cddlib-094h.tar.gz
	    CONFIGURE_COMMAND ${CDD_PROJECT_SRC_DIR}/configure --prefix=${CMAKE_INSTALL_PREFIX} CXXFLAGS='-I/opt/local/include'
	    BUILD_COMMAND make
	    BUILD_IN_SOURCE 1
	    )
	set(iris_dependencies ${iris_dependencies} cdd_project)
endif()
```

**Comment by rdeits** [comment]
Ah, interesting. Does setting CFLAGS instead work? (since cddlib is a C, not C++, library)

**Comment by edowson** [comment]
I didn't try setting CFLAGS. The CMakeLists.txt wasn't set up to be modular, to detect whether HomeBrew or MacPorts was used to install gmp.

I've put in an enhancement request to consider migrating the entire drake system and it's libraries to a catkin (ROS) based one. It's easier to manage a build workspace and create modular projects that export the required libraries and headers.

RobotLocomotion/drake#1423

**Comment by edowson** [comment]
I submitted a pull request for the following commit:

edowson/iris-distro@6babfc0b09b1795ed7dd79726e585640303b7458

but it failed the continuous integration test because some compiler environment variables were not set.

https://travis-ci.org/rdeits/iris-distro/builds/85168593

The patch doesn't affect any source files or the build system, just adds some missing pre-requisites for completing a MacPorts installation. Do you think you could take a look?

**Comment by rdeits** [comment]
No problem--that's actually expected. I have an encrypted copy of my personal Mosek license which is decrypted on the CI servers in order to run their tests. But that decryption is disabled for pull requests which come from other repositories, since otherwise a bad actor could modify the test script to steal the decrypted data (not that I actually care in this case, but it's a protection built into the CI system). I've merged your PR, and I'll try to figure out a better way to handle them in the future.
