### ISSUE TITLE
iris doesn't install solver.h

### ISSUE THREAD

**Issue by mauricefallon** [rdeits/iris-distro#31]
I recently updated mitdrc/drc but the new distro of iris doesn't install solver.h.
As a result QPReactiveRecovery won't compile.

This fix is sufficient to correct the issue:
https://github.com/rdeits/iris-distro/compare/master...mitdrc:solver-header-install

Can we roll that into iris or was there a reason behind not installing this?

**Comment by rdeits** [comment]
Okay, thanks for finding that. I've updated IRIS master with that fix.
