### ISSUE TITLE
cddlib download uses unreliable ftp server

### ISSUE THREAD

**Issue by jwnimmer-tri** [rdeits/iris-distro#41]
The current `iris-distro` downloads the cddlib tarball from a slow and unreliable FTP server.  This is causing headaches for Drake's continuous integration.

It would be better if the cddlib tarball came from somewhere more reliable.  Perhaps we should re-host it, or select a more reliable existing host.

See also RobotLocomotion/drake#2771.

**Comment by rdeits** [comment]
I'm open to any of those. There's also this github fork: https://github.com/mcmtroffaes/cddlib which [pycddlib](https://pypi.python.org/pypi/pycddlib/) uses, but I can't vouch for it personally.

**Comment by jwnimmer-tri** [comment]
Thanks.  I will work with TRI and/or Kitware to get a PR prepared here that switches over the hosting.
