### ISSUE TITLE
addpath_iris, rmpath_iris are gone

### ISSUE THREAD

**Issue by wxmerkt** [rdeits/iris-distro#58]
Just noticed that as of #52 these files are gone - is there a replacement or should we re-add them?

**Comment by rdeits** [comment]
They should no longer be necessary. The entire iris Matlab package is now copied to the matlab folder on install, so there's no need to modify the path at all.

However, the Matlab bindings will slower, because I'm no longer compiling any Mex files for them.

**Comment by wxmerkt** [comment]
Thanks for the response. I've found a workaround, cf. https://github.com/openhumanoids/oh-distro-private/pull/2643

**Comment by wxmerkt** [comment]
Thanks for all your help - now resolved.

**Comment by rdeits** [comment]
Great!
