### ISSUE TITLE
 could not find git for clone of mosek

### ISSUE THREAD

**Issue by YuanfeiLin** [rdeits/iris-distro#77]
Hi all,

i tried to install irispy in my ubuntu system, and I already download and activate the mosek. Why does the following fault still appear after I input cmake .. :

CMake Error at /snap/cmake/340/share/cmake-3.17/Modules/ExternalProject.cmake:2454 (message):
  error: could not find git for clone of mosek
Call Stack (most recent call first):
  /snap/cmake/340/share/cmake-3.17/Modules/ExternalProject.cmake:3267 (_ep_add_download_command)
  CMakeLists.txt:102 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!

Thanks a lot in advance!

**Comment by Feng-Kaijun** [comment]
hello, i have the same error. please help!!!
