### ISSUE TITLE
could not find git for clone of mosek

### ISSUE THREAD

**Issue by Feng-Kaijun** [rdeits/iris-distro#87]
Hi, in the CMakeLists.txt, the [GIT_REPOSITORY]( https://github.com/RobotLocomotion/mosek.git) of mosek is invalid. And i had installed mosek in ubuntu20. So what can i do for linking iris with mosek ?

**Comment by carlchan0514** [comment]
I had the same problem

**Comment by Feng-Kaijun** [comment]
> I had the same problem

Hi, i have a way to make the mosek7 work. You can fork this [repo](https://github.com/Feng-Kaijun/mosek7), and replace the original link (Line 104 & 105) in the top CMakeList. 
We should pay attention that the IRIS project only can support mosek7, although there is now the latest mosek10. I tried to update mosek from 7 to 10, but some [Constants](https://docs.mosek.com/9.3/capi/changes.html?highlight=msk_sol_sta_near_prim_infeas_cer) about MSK_SOLSTA_NEAR_XXXXXX had been removed in mosek9. Therefore this IRIS project can not be compatible with mosek9 & 10, if you don't update corresponding codes. 
I tested that : mosek10, not work; mosek7 work.
